# if you want to configure triggers for Azure CI see
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#tags
jobs:

  # Example job that runs end-to-end tests using Cypress test runner
  #   https://www.cypress.io/

  # Job names can contain alphanumeric characters and '_', cannot start with a number
  - job: Cypress_e2e_tests
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      parallel: 1
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
          displayName: 'Install Node.js'

      # Install Node dependencies
      # TODO How to cache ~/.npm and ~/.cache folders?
      # https://github.com/cypress-io/cypress-example-kitchensink/issues/132
      #- script: npm ci
      #  displayName: 'Install NPM dependencies'


      # The next command starts the server and runs Cypress end-to-end tests against it.
      # The test artifacts (video, screenshots, test output) will be uploaded to Cypress dashboard
      # To record on Cypress dashboard we need to set CYPRESS_RECORD_KEY environment variable
      # environment variable BUILD_BUILDNUMBER is a good candidate
      #- script: npm run test
      #  displayName: 'Run Cypress tests'


      - bash: |
          token="$(curl -H "Content-Type: application/json" -X POST --data '{"client_id":"$(client_id)","client_secret": "$(client_secret)"}' https://xray.cloud.xpand-it.com/api/v1/authenticate| tr -d '"')"
          echo "this is my test"
          echo ${token}
          curl -H "Content-Type: text/xml" -X POST -H "Authorization: Bearer ${token}" --data @test-results.xml  https://xray.cloud.xpand-it.com/api/v1/import/execution/junit?projectKey=$(project_key)
